import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		double couples = Double.parseDouble(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		int childrenCount = 0;
		int twoChildren = 0;
		int threeChildren = 0;
		int fourPlus = 0;
	for (int i = 0 ; i < couples ; i++){
		int localCount = 2;
		String Gender1;
		String Gender2;
		double random1= generator.nextDouble(); //getting a number between 0 to 1 
			if (random1<0.5){
				Gender1 = Double.toString (random1);
				Gender1="g";
			} 
			else{
				Gender1 = Double.toString (random1);
				Gender1="b";
			} 
			// System.out.print(Gender1 + " ");
			double random2= generator.nextDouble();
			if (random2<0.5){
				Gender2 = Double.toString (random2);
				Gender2="g";
			} 
			else{
				Gender2 = Double.toString (random2);
				Gender2="b";
			} 
			childrenCount = childrenCount + 2;
			// System.out.print(Gender2 + " ");
			while (Gender1 == Gender2){
				childrenCount++; 
				localCount++;
				Gender1=Gender2;
				random2= generator.nextDouble();
				if (random2<0.5){
					Gender2 = Double.toString (random2);
					Gender2="g";
				} 
				else{
					Gender2 = Double.toString (random2);
					Gender2="b";
				} 
				// System.out.print(Gender2 + " ");
			}
			if (localCount == 2 ){
				twoChildren++;
			}
			if ( localCount == 3 ){
				threeChildren++;
			}
			if (localCount >= 4){
				fourPlus++;
			}
		}
			System.out.println();
			System.out.println("Average: " + childrenCount/couples + " children to get at least one of each gender.");
			System.out.println("Number of families with 2 children: " + twoChildren);
			System.out.println("Number of families with 3 children: " + threeChildren);
			System.out.println("Number of families with 4 or more children: " + fourPlus);
			if (twoChildren > threeChildren && twoChildren > fourPlus){
				System.out.println("The most common number of children is 2." );
	
			}
			if (threeChildren > twoChildren && threeChildren > fourPlus){
				System.out.println("The most common number of children is 3." );
	
			}
			if (fourPlus > twoChildren && fourPlus > threeChildren){
				System.out.println("The most common number of children is 4 or more." );
	
			}
   }
		    
}